version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./datebase:/var/opt/mssql 

  # flask_app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: flask_container
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mssql
  #   environment:
  #     FLASK_APP: run.py
  #     FLASK_ENV: development
  #     DATABASE_URL: "mssql+pyodbc://sa:Password123@mssql:1433/ReportDb?driver=ODBC+Driver+18+for+SQL+Server"
  #   volumes:
  #     - ../app:/app  # ✅ 確保 Flask 應用可用
  #     - ../run.py:/app/run.py  # ✅ 確保 run.py 存在
